spring:
  application:
    name: blogapi

  datasource:
    url: jdbc:postgresql://localhost:5432/blogdb
    driver-class-name: org.postgresql.Driver
    username: bloguser
    password: blogpass

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true